### ISSUE TITLE
自动造词时算法的改进

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#100]
I got it now. Leave this at the moment.

输入：vsq gow gud dme myl vuf，中国古典名著，中间古典，出来的是“古点”，有办法改进吗？

and, dvv rfl qyo uif lid, 对人情事理，出来的应该是“事理”而不是“事李”。

**Comment by Sunddyy** [comment]
存在词组 “中国古” 导致怪异组合。

**Comment by sicilian-lizard** [comment]
发现了。问题关闭。
