### ISSUE TITLE
删除编码之后，应该重新获得检索结果

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#147]
现象：输入jia，然后翻页至非常用字，然后删除a，候选字应等于直接输入ji时的候选字。

**Comment by Sunddyy** [comment]
已经从新查找，只不过是是在非常用字范围。（这个再议，不一定正确）你翻页的目的什么呢？

**Comment by sicilian-lizard** [comment]
问题依旧。但如果不区分常用字和非常用字之后，这个问题应该就不存在了。

所以先关闭。
