### ISSUE TITLE
Word中，切换到英文状态，只能输入一个字母，然后就又是中文状态了。

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#209]

**Comment by Sunddyy** [comment]
是由于进入汉字系统后默认我行子方式这个功能造成的，word发送的消息和刚进入汉字系统的消息一样，导致一个英文之后，系统好从新进入了汉字系统（此时进入汉字状态）。因此暂时取消进入汉字系统后，默认为汉字状态的功能（以后再完善这个功能）

**Comment by sicilian-lizard** [comment]
切换进输入法默认为中文状态这个功能比较重要，想想办法吧。

**Comment by sicilian-lizard** [comment]
问题已消失，改了？

**Comment by sicilian-lizard** [comment]
问题已消失，先关闭。
