### ISSUE TITLE
*** 进入造词状态后，改变编码后，应退出造词状态。

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#216]
原标题：造词时，已经选定的字在修改编码之后会变回自动选定的字。

有两种解决方法：
1. 修改编码直接退出造词状态。（我倾向于这一种）
2. 修改编码不退出造词状态，前面已选定的字不变，修改后的编码重新检索。

可以设成可选项。

**Comment by Sunddyy** [comment]
这个问题想了想，正解比较复杂，先删除吧。场景如下;若果修改选择了部分单字，自动组词的功能就非常麻烦，有可能出现分段判断的情况（zxxbxxc，xx的地方是没改过的，有两个xx，组词算法要改进才行）

**Comment by sicilian-lizard** [comment]
我觉得也是，所以我建议修改编码后直接退出造词状态，可以避免因为输错而进入造词状态只能清除编码的情况，同时避免了很多问题。

比如我输入要输入“可能”，编码输成了“kedngv”，本来空格是为了上屏，结果却进入了造词状态，这时候，删掉一个编码，如果退出造词状态，就可以直接修改了。

现在不退出，因为不能保留前面已经选定的字，不但没有意义，反而容易造成错误。比如，造一个三字词，我前面选定了两个字，到第三个字的时候，发现编码输错了，于是删编码，结果前面已经选定的字可能已经又变回自动选定的字了，而这时候我的注意力全在第三个字上，选定了第三个，空格上屏，结果这时候很可能就造了一个错词。

删编码后退出造词状态虽然不能完全避免这种可能，但却避免了因输错而误进入造词状态的情况，而这种情况比真的是想造词的情况要多多了。

**Comment by sicilian-lizard** [comment]
已解决。
