### ISSUE TITLE
*** 背景图片闪，似乎是因为画了两次，而且两次的长度不一样。

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#225]
一次是默认长度，一次是计算而得的长度。默认长度在只出候选框不出候选字的时候可以看出来，和显示候选字时的长度是不一样的。

默认长度我觉得刚好合适。

**Comment by Sunddyy** [comment]
已经尝试修改，进一步修改需要花时间，可能是系统缓存。

**Comment by sicilian-lizard** [comment]
感觉以前是上屏之后，候选框是被隐藏了，所以下次输入的时候，原来的先被显示，然后又清掉画新的。所以会闪一下。

而现在，是先画了一个，然后在输入编码之后，又画了一次。所以那种d和空格同时按而不出候选字的时候，候选框的长度和有候选字的时候的长度是不一样的。

**Comment by sicilian-lizard** [comment]
已解决。
