### ISSUE TITLE
*** 造词选字时，候选字不应出现词。

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#228]
输入nalelo，第一个字选拿，选第二个字的时候，候选字出现了词“爱洛伊丝”

Update: 上述问题已消失，但新问题是，无字可选时应依例用红色显示编码和问号。

**Comment by Sunddyy** [comment]
造词时，当然要查词库，是取默认值。你这个要分析问题的本质。

**Comment by sicilian-lizard** [comment]
取默认值当然没问题，但用户逐字选定的时候，就不应该再查词库。尤其是在后面的编码长度<3的时候。

**Comment by Sunddyy** [comment]
已经处理。

**Comment by sicilian-lizard** [comment]
已解决。
