### ISSUE TITLE
去掉task manager中的ISUI窗口。

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#25]
这个ISUI进程，好像是每一个打开我们的输入法的应用程序都会打开一个。

**Comment by Sunddyy** [comment]
我这里没有，不具普遍性。

**Comment by sicilian-lizard** [comment]
你那里没有这个吗？

![isui](https://cloud.githubusercontent.com/assets/4833223/12320438/b35ce28c-bae3-11e5-8d23-30a6db4c0f19.jpg)

**Comment by Sunddyy** [comment]
这是程序，不是进程，你要注意说清楚。这是输入法的初始化窗口，已经隐藏掉。

**Comment by sicilian-lizard** [comment]
fixed
