### ISSUE TITLE
如果单字显示完了，按翻页键开始显示非常用字。

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#3]
在输入的编码在4码（含）之内，按翻页键到底，开始显示非常用字。

如输入编码gea，第一页显示： 歌 哥 搁，第二页显示：戈 圪 格，常用字至此已经全部显示。再次按翻页键的时候，开始检索显示非常用字。

**Comment by Sunddyy** [comment]
这个功能实际上和显示全部单字是一致的，怎么区分呢？除非再增加常用和非常用的提示，否则显示全部单字即可。

**Comment by sicilian-lizard** [comment]
不一致。

一般情况下，常用的8000字足够了，显示剩下的14000字，徒增其扰。但有时候偶尔会用到非常用字，这个时候最好能有一个比较方便的方法来输入非常用字。

比如我要输入“楛"字，这个是个非常用字，词频0。我输入编码kud，结果只有”苦“字，这个时候我按一下翻页键，就显示词频为0的字，就能输入楛字了。

也就是说，等常用字显示完了，再按翻页键，再查询显示词频等于0的非常用字。

你设定的那个 limit 64也可以这样解决，就是，检索到的64个字显示完了，再按翻页键，检索并显示所有常用字。

**Comment by sicilian-lizard** [comment]
现在，按翻页键好像会和造词冲突，改成某个组合键行不行？比如SHIFT+>?

**Comment by sicilian-lizard** [comment]
Done!
