### ISSUE TITLE
*** 有的时候，有时只出待选窗口，不出字。

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#38]
必须ESC关掉候选窗口，才能再出字。比较难以重现，但时有发生。

出现几率较少，待后期再解决吧。
https://cloud.githubusercontent.com/assets/4833223/12045872/24f29e7c-aee7-11e5-919e-2a66d8fe79e6.jpg

**Comment by Sunddyy** [comment]
就是输入太快造成的，系统此时判定完成两个键同时按下。判断两键同时按下的快速算法还没找到，只处理了D键。

**Comment by sicilian-lizard** [comment]
这样处理的结果造成上屏了一个空格，而要输出的“的”没有上屏。并没有比以前好。没有解决办法之前，先不要这样解决吧。

**Comment by sicilian-lizard** [comment]
终于可以把这个问题关闭了。已解决。
