### ISSUE TITLE
字频、词频保存错误。

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#40]
如，wuj，选择第二个字的时候，结果第一个字的字频增加了，第二个字反而没有增加。选第三个字，字频也是加在第一个字上了。

同样，词频也是如此，如 uifuif, 选第二个第三个词的时候，词频加在了第一个词的上面。

**Comment by Sunddyy** [comment]
Fixed.

**Comment by sicilian-lizard** [comment]
Fixed and closed.
