### ISSUE TITLE
造词问题汇总

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#44]
1、已解决。~~造词时的待定词的符号，还是用全角符号吧，如果全角问号不能用，还是用原来的全角星号吧。~~
2、已解决。~~进入造词状态后，第一个问号没有用蓝色显示。应该统一高亮风格，移动光标时的高亮也用蓝色字体显示，而不用背景色。例如：bopnalbaz, 用向左键移动光标。
更新描述：输入fzqihw，然后按翻页键进入造词状态，第一个字及其编码没有高亮。~~
3、已解决。~~???: 输入编码 gofduu，按翻页键进入造词状态，上面不应该显示已有的词。~~
4、已解决。~~输入编码 kedlejked，按向上键头键，再按空格键选字，结果选定的不是第二个字，而是第一个字。~~
5、已解决。~~???: 造词的时候，按上下方向键移动光标时，应移动到上下字的末尾，而不是当前位置-3或+3的位置。~~

6、候选字只有一个的时候，为保持一逻辑致，以及以后的非常用字的选择，去掉自动选定该字的功能。不要自动选字功能。

7、暂不处理：当编码对应有单字时不分解显示。按3个编码一组处理。

问题不成立。~~进入造词状态后，编辑已输入的编码，然后，待选字不完全对，如输入 uuzdeh, 按向左键，从e开始删除edz，再输入zde，第一组编码uuz的待选字和直接输入uuz是不一样的，少。~~

8、已解决。~~造词时，正在选的字用 RGB 0, 136, 208显示，输入的编码，按声韵检索不到备选词时，字体颜色显示为红色。去掉高亮背景色。~~

9、造词时，除非用户自己移动光标，光标一直放在最后。选定了单字之后，按删除键，先逐个删除前面一个已选定的单字，再删除编码。

10、已解决。~~???: 进入造词状态后，向前翻页退出造词状态，回到正常输入状态。如uiwuif，发现没有要的词，向后翻页进入造词状态，向前翻页则退出造词状态，重新显示已有的词。~~

11、进入造词状态后，光标移动到最后时，不要出现词库中已有的词，否则容易误解。比如，输入fzqihw，按>进入造词状态，将光标移到最后，再移到第一个字的编码，就不能选字造词了。

12、已解决。~~: 更新描述：在保存自造词的时候，检查词库中是否已经有该词时，要同时检查编码。汉字相同而编码不同时，也要保存为新词。
原描述：新造的词，只有库中已有这个词，且其编码和现在试图在造的词的编码也相同的时候，才不保存这个新词。比如，大黄，中医中念 dai4 huang2, 编码是dlfhds, 而我有一条狗，起名叫大黄，于是我造词，这时候编码是dafhds，这个词要按这个编码保存为新的词。~~

13、从第六码开始，如果候选项为空，或在用户翻页至候选项末尾，且用户输入的编码长度为3的整倍数时，再次按翻页键，自动进入造词状态。候选项依次显示以每3码检索出的单字，供用户选定。**如果候选项不为空（包括有备选单字），不自动进入造词状态。必须在用户翻页至候选项末尾时再进入造词状态。**

14、关闭。 ~~有时无法选择第二个字。如：输入fzqihw，选第一个字，然后按翻页键>，本来应该显示第一组编码对应的字，现在显示的是第二组编码的字。~~

15、 有字的时候，按翻页键再进入造词状态。如xpoygh. 此问题和#13重复。

16、 造词时，选定第一个字，然后修改编码至第一组编码，然后再输入第二组编码，则不显示第一组编码对应的字了。如：造词“农书”，输入nsouuz，选定第一个字“农”，然后假设发现第二组编码输错了，然后删除，假设删多了，删到了o，然后再输入ouuz，这时候就不能显示第一组编码对应的字了。

17、暂不处理。 造词时，待确定字用比较淡的颜色显示？

18、bug, 输入fzqih，按翻页键>，显示非长，这里只有5码，不应该进入造词状态。4码的时候也是如此，如输入gdqb，按> （在Word中有此问题，在IE中无）。

19、输入fzqihw，选第一个字，然后按翻页键>，又回到了第一个字。任何时候，翻页键不应移动光标。

**Comment by Sunddyy** [comment]
已经标上编号,这样便于描述和回应。
1、已经使用全角星号，这个将来可以作为配置项。
2、背景高亮已经改为字体高亮，但是效果不如背景高亮明显，这个也考虑改为可配置项；
3、已经修改。
      cause:刚进入造词模式时，没有设置默认的词组第一单字的索引值（0）
4、已经修改
     cause：人工移动光标之后没有退出自动造词模式。
5、已经修改。
6、暂不修改，不影响使用（后一种逻辑和当前逻辑一致，只是显示不同）
7、不能重现。
8、已经修改。
9、pending
10、已经修改
11、已经修改，并增加退出提示。需要拷贝winddow ding.wav 到输入法根目录。目前暂定为 C:\Users\Public.
12、不能重现。
13、原描述不清，按翻页键是人工造词模式。建议修改为：3的整数倍时，符合条件自动进入造词模式。

**Comment by Sunddyy** [comment]
请标上编号。
1、已经使用全角星号，这个将来可以作为配置项。
2、背景高亮已经改为字体高亮，但是效果不如背景高亮明显，这个也考虑改为可配置项；

**Comment by sicilian-lizard** [comment]
1. ~~我这里还是显示的是英镑的符号£，是字符集的问题？~~
2. ~~输入fzqihw，然后按翻页键进入造词状态，第一个字的编码及对应的＊没有高亮。~~
3. 确认。
4. ~~输入kedlejked，按向上箭头将光标移至第二字，选定”可“字，然后选定第三个字，这时候保存的词是£乐可。如果没有选定每个字，不要保存造词，任何时候，造的词中不应含有待选字符号（£，？，或＊，不管用哪一个）。~~
5. 确认。
6. 下面的工作中，如果造词要用到非常用字，这个可能会有影响。
7. 描述已更新。
8. 参见本集第一个问题。
9. 先放着。
10. 确认。
11. 改过之后，光标移到最后时仍旧出现词库中已有的词。另外，不要加声音。
12. 描述已更新。 
13. 测试中，基本就是这个意思。到第六码，自动进入造词状态的时候，在输入的编码个数非3的整数倍时，继续输入编码，可以一直显示第一个字的待选字，不必来回切换状态。比如，造词“事非经过不知难”，uiffzqjyzgofbufvimnjx, 从第六码开始进入造词状态之后，那个“事”字就应该一直在那里。

**Comment by Sunddyy** [comment]
11 那是因为已经退出造词状态，提示音是提示即将退出造词状态，我认为还是有意义的。

**Comment by sicilian-lizard** [comment]
未解决的问题转入#61。关闭。
