### ISSUE TITLE
如果能检索到词，则输入的编码不以红色显示。

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#45]
如，便宜 pmlyiy. 因为能检索到词，所以不要用红色显示编码。只有检索不到词，而且也检索不到单字的时候，再用红色显示编码，表示输入的编码错误。

**Comment by Sunddyy** [comment]
Fixed。
但是保留了，移动光标到该子编码时，仍然变红（无对应字时）。

**Comment by sicilian-lizard** [comment]
OK. Good point!

但词组中没有解决。便宜，输入pmlyiy，yiy仍旧是红色。

**Comment by sicilian-lizard** [comment]
编码用红色字，我想的是在原来的基础上，输入像pmlyiy“便宜”这样的词时，虽然yiy查不到宜，但pmlyiy可以查到“便宜”，所以yiy在这个时候也不用红色显示。其余的用原来的就行。

例如，输入uiwja，uiw能查到字，黑色，ja查不到词，用红色。

**Comment by Sunddyy** [comment]
这个没有必要吧，查不到就是查不到。pml 是正常颜色，yiy是红色，正好表征。其他颜色，也就表达这个意思，而且这种词很少。用户估计也不会采用这种方法造词。

**Comment by sicilian-lizard** [comment]
有必要。红色字体只表示一个意思，就是输入的编码有误，所以检索不到。已经检索到了，无论是字是词，证明输入编码无误。

这种词其实很不少，而且都是常用词，因为基本只有常用词，才会因为口语的影响而产生变调。

比如，消息，精神，逻辑，实在，结实，事情，交情，等等。

**Comment by Sunddyy** [comment]
前面的正常颜色+红色是一种状态，这种组合有四种状态。全红是找不到。

**Comment by sicilian-lizard** [comment]
输入fzqja，fzq是能找到字的，用正常颜色，ja找不到，用红色。

**Comment by sicilian-lizard** [comment]
Done.
