### ISSUE TITLE
界面调整

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#47]
1. ~~序号和候选字下端对齐。~~
2. ~~序号和其对应的候选字之间的距离减少一点。大约是现在的2/3。~~
3. ~~编码和序号1左对齐。~~
4. 如果输入的编码有词，而按翻页键进入造词状态，第一个字没有用蓝色显示。
5. 造词时，待定字的符号在我这里还是显示为£。请解决，或是改用＊号吧。
6. ~~编码之间的那个虚拟的空格，稍微增大一点。~~

**Comment by Sunddyy** [comment]
1 2 和字体有关，可以先暂时调整。
3 已经修改
4、不清楚
5、已经修改
6、从3 pix 调整至5pix（和字体有关）

**Comment by sicilian-lizard** [comment]
1、2，字号太大了，而且改用consolas。
3 确认。
4 输入fzqihw，按翻页键，第一个字没有用蓝色显示。
5 没有改过来啊。
6 等改为consolas之后再看。

**Comment by Sunddyy** [comment]
建议：关掉时，简单写上理由。

**Comment by sicilian-lizard** [comment]
大部分问题已解决，剩下的两个移到#44。
