### ISSUE TITLE
按翻页键>进入造词状态后，按<退回到输入状态。

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#54]
按翻页键>进入造词状态后，按<应该退回到输入状态。

**Comment by Sunddyy** [comment]
updated。

**Comment by sicilian-lizard** [comment]
问题本已解决，现在的版本，按<没有任何反应了。

**Comment by Sunddyy** [comment]
我这里不存在。

**Comment by sicilian-lizard** [comment]
我演示给你看。

**Comment by sicilian-lizard** [comment]
输入fzqihw，按翻页键进入造词状态，再按向前翻页键<应退回到正常输入状态。

**Comment by Sunddyy** [comment]
这个要看光标的位置，光标在第一个单字上才有效（目前是这样）。如果不是第一个单字，会造成混乱。进入造词之后，<> 键是用来选字的，赋予其他功能必须清楚才行。建议使用esc退出当前状态（逐步退出，直到退出所有状态）。

**Comment by sicilian-lizard** [comment]
如果决定使用手动进入/退出造词状态，这个问题就无效了。
