### ISSUE TITLE
词组PK不能正确保存。

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#6]

**Comment by Sunddyy** [comment]
Fixed. 
Cause: The usage of last_insert_rowid() is not correct. 
Action: Re-create the phrase table with a primary key. Using the attatched file to update the DB. 
Step: 1 Run Phrase.bat,Word.bat
         2 Run CopyDB.bat
         3 register the latest version of imesample.ime
If faliled, log off from the OS and then do as the above described.

**Comment by Sunddyy** [comment]
[UpdateDB.zip](https://github.com/sicilian-lizard/wandou/files/60696/UpdateDB.zip)

**Comment by Sunddyy** [comment]
[UpdateDB.zip](https://github.com/sicilian-lizard/wandou/files/60747/UpdateDB.zip)

**Comment by Sunddyy** [comment]
[imesample.zip](https://github.com/sicilian-lizard/wandou/files/60748/imesample.zip)

**Comment by sicilian-lizard** [comment]
Done and closed.
