### ISSUE TITLE
造词问题汇总二

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#61]
前造词问题汇总已关闭，全部合入本问题。
- [x] 1. 光标放最后，除非用户用箭头键移动光标，不要自动移动光标。
- [x] 2. 选定字之后，删除键先依次删除选定的字，再删除编码。
- [x] 3. 如果用户移动光标至某组编码，再按删除键，直接删编码，然后更新检索结果。
- [x] 4. 在造词状态中，移动光标到最后，不要显示已有词。
- [x] 5. ~~将“造词”这个提示词，放在待造词前面，字体颜色用灰色8号字。~~
- [x] 6. 自动选定字的字体颜色用淡灰色，选定之后改成黑色。已选定了的字被删除之后之后，改回淡灰色。将自动选定字设为可选项。
- [x] 7. 已实现：设置一个快捷键将自动选定的词上屏?
- [x] 8. 问题作废。~~待讨论：如果待造词的每个待选字都惟一，自动造词?~~
- [x] 9. 问题作废。~~待讨论：选定第一个字之前，不显示待定字位？~~
- [x] 10. 问题已无效。~~按翻页键>进入造词状态后，按向前翻页键没有退回到正常输入状态。~~
- [x] 11. 输入编码错误之后，再输入一组编码，错误编码的待选字有错误。如，输入rujruqjj，第二个字应该用问号显示。
- [x] 12. 输入的编码中，只有没有检索到单字的那组编码用红色字体显示。如，输入jpapp，jpa是能检索到字的，不应用红色字体。
- [x] 13. 编辑编码时，出现两个字高亮。如输入dhqdhqdhq，选定第一个字，按向上箭头键，再按删除键。
- [x] 14. 用上下箭头移动光标时，应该移动到上一组编码的末尾。即使光标是在本组编码的中间，或本组编码长度小于3。
- [x] 15. 选字的时候，第一次按翻页键>, 没有翻页。如：qxuyus，按翻页键。
- [x] 16. 问题作废。~~输入9个以上编码，进入造词状态后，如果删除编码，应退出造词状态。如输入yisjujhwj，如果删除j，应该显示已有词，”一句话“。和两字词的逻辑一样。~~
- [x] 17. 输入的代码能检索到单字的时候，不要自动进入造词状态。如输入qxuytg。
- [x] 18. 造词状态的进入和退出。放弃自动进入造词状态，只有在已有字词显示完，按翻页键，再进入造词状态。按ESC退出造词状态。这样以后，刚实现的按删除键首先删除已选定的字也就失去了意义，再改回来吧，按删除键直接删除编码。
- [x] 19. 造词时，翻页选字之后，就不能正确显示下一组编码的候选字了。如：造词黛瓦，dljwak，黛在第二页，选定之后，没有正确显示wak对应的汉字。
- [x] 20.

**Comment by Sunddyy** [comment]
1、已经是这样；
2、因为存在默认候选字（词组），这个删除过程除非从新做标记，否则没有意义。另外，可以移动光标直接修改。另外如果要直接修改编码，岂不是要做完这些操作才能修改？
3、目前就是这样；
4、目前就是这样；
5、待修改；
6、待修改；
7、按0即可；
8、不存在自动造词的概念，只是默认提示而已，按0 即可确认这个默认词组；
9、不懂。

**Comment by sicilian-lizard** [comment]
All done!
