### ISSUE TITLE
造词时候选字的问题

### ISSUE THREAD

**Issue by sicilian-lizard** [sicilian-lizard/wandou-win#73]
造两字词的时候，如果是新词，选第二个字的时候，显示的还是第一组编码的候选字。如果已有词，按翻页键造词，就没问题。

造词 骂成，marigs，第一选骂，等第二个字的时候，候选字还是mar对应的字。

**Comment by sicilian-lizard** [comment]
第二个字选第二页的字的时候，还是有同样的问题。

**Comment by Sunddyy** [comment]
没懂。

**Comment by sicilian-lizard** [comment]
有时间的时候我演示给你看吧。

**Comment by sicilian-lizard** [comment]
问题不存在了。
